baseURL = 'https://johnbntn.github.io'
languageCode = 'en-us'
title = 'Some Interesting Things'
theme = 'paper'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  math = true
  name = 'Recent Posts'
  bio = ' '
  github = 'johnbntn'

[[menu.main]]
  name = 'Main Content'
  url = "/"
  weight = 5

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 10

[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20